#!/bin/sh

# Ddefault layout
riverctl default-layout rivertile

# Appearance
riverctl background-color 0x000000
riverctl border-color-focused 0xff7a93
riverctl border-color-unfocused 0x00ffd2
riverctl border-width 2

# Cursor
riverctl focus-follows-cursor normal
riverctl hide-cursor when-typing enabled

# Mouse
riverctl map-pointer normal Super BTN_LEFT move-view      
riverctl map-pointer normal Super BTN_RIGHT resize-view   
riverctl map-pointer normal Super BTN_MIDDLE toggle-float 

# Keyboard layout
riverctl keyboard-layout pt

# Terminal
riverctl map normal Super Return spawn foot

# Close window
riverctl map normal Super Q close

# Close Session
riverctl map normal Super+Shift Q exit

# App launcher
riverctl map normal Super D spawn fuzzel

# File manager
riverctl map normal Super S spawn thunar

# Start layout generator (blocks)
exec rivertile -view-padding 1 -outer-padding 1

# Start status bar
yambar &
